<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = Carbon::now();

        DB::table('products')->insert([
            [
                'product_name' => 'ペティーナイフ',
                'product_code' => '001',
                'product_quantity' => '3',
                'selling_price' => '7700',
                'discount_price' => NULL,
                'category_id' => '1',
                'subcategory_id' => '3',
                'brand_id' => '6',
                'product_size' => '13cm',
                'product_color' => 'シルバー',
                'product_details' => '小型なので野菜や果物などの細工・飾り切りに適しています。 特に切っ先付近の鋭いカーブを活かして「引き切り」に重宝します。',
                'video_link' => 'https://www.youtube.com/watch?v=wLK-tsCGwSI',
                'status' => '1',
                'hot_new' => '1',
                'trend' => '1',
                'best_rated' => '1',
                'hot_deal' => '1',
                'main_slider' => '1',
                'mid_slider' => '1',
                'buyone_getone' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_name' => 'V60レンジサーバー',
                'product_code' => '002',
                'product_quantity' => '5',
                'selling_price' => '3000',
                'discount_price' => '2700',
                'category_id' => '1',
                'subcategory_id' => '2',
                'brand_id' => '5',
                'product_size' => '1-3杯用, 2-5杯用, 2-6杯用',
                'product_color' => '透明ブラック',
                'product_details' => 'ポット・フタとともに耐熱ガラス製。フタにはシリコンパッキン付きの安心設計です。フタをしたまま電子レンジOK。',
                'video_link' => NULL,
                'status' => '1',
                'hot_new' => '1',
                'trend' => '1',
                'best_rated' => '1',
                'hot_deal' => NULL,
                'main_slider' => '1',
                'mid_slider' => NULL,
                'buyone_getone' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_name' => 'オーブンポットラウンド',
                'product_code' => '003',
                'product_quantity' => '10',
                'selling_price' => '29990',
                'discount_price' => '25000',
                'category_id' => '1',
                'subcategory_id' => '1',
                'brand_id' => '3',
                'product_size' => '18cm, 20cm, 22cm',
                'product_color' => 'ナチュラルベージュ, ストーン, マットブラック',
                'product_details' => '直火・IHクッキングヒーター対応のバーミキュラがイチオシするホーローコーティングの鍋。',
                'video_link' => NULL,
                'status' => '1',
                'hot_new' => '1',
                'trend' => '1',
                'best_rated' => '1',
                'hot_deal' => '1',
                'main_slider' => '1',
                'mid_slider' => '1',
                'buyone_getone' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_name' => 'ベルコード 二折札入れ',
                'product_code' => '004',
                'product_quantity' => '5',
                'selling_price' => '51700',
                'discount_price' => NULL,
                'category_id' => '5',
                'subcategory_id' => '13',
                'brand_id' => '16',
                'product_size' => '外寸=縦9.0×横11.1×最大マチ2.5㎝',
                'product_color' => 'ブラック, ブラウン',
                'product_details' => 'スマートに携え優雅に使いこなす、薄くコンパクトな二折財布。',
                'video_link' => NULL,
                'status' => '1',
                'hot_new' => '1',
                'trend' => '1',
                'best_rated' => '1',
                'hot_deal' => '1',
                'main_slider' => '1',
                'mid_slider' => '1',
                'buyone_getone' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_name' => 'ローチェア30',
                'product_code' => '005',
                'product_quantity' => '10',
                'selling_price' => '16000',
                'discount_price' => '14000',
                'category_id' => '2',
                'subcategory_id' => '6',
                'brand_id' => '11',
                'product_size' => '30',
                'product_color' => 'ブラウン, カーキ',
                'product_details' => 'とにかく座ってみてください!立ち上がりたくなくなるリラックス感、なのに食事も作業もしやすい安定感。コンパクトに収納できて、自宅でもうれしいローチェアです。',
                'video_link' => 'https://youtu.be/w55Ipfy-_5c',
                'status' => '1',
                'hot_new' => '1',
                'trend' => '1',
                'best_rated' => '1',
                'hot_deal' => '1',
                'main_slider' => '1',
                'mid_slider' => '1',
                'buyone_getone' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_name' => 'LifE',
                'product_code' => '006',
                'product_quantity' => '15',
                'selling_price' => '3960',
                'discount_price' => NULL,
                'category_id' => '2',
                'subcategory_id' => '5',
                'brand_id' => '8',
                'product_size' => '60cm×125cm',
                'product_color' => 'オフホワイト, ベージュ, ブルーグレー',
                'product_details' => '世界有数の外資系ホテル18社で採用された（R元年9月末時点）タオルをご家庭用にリメイクしたもので、優しい肌触りと持続性、耐久性を兼ね備えています。',
                'video_link' => NULL,
                'status' => '1',
                'hot_new' => '1',
                'trend' => '1',
                'best_rated' => '1',
                'hot_deal' => '1',
                'main_slider' => '1',
                'mid_slider' => '1',
                'buyone_getone' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
